display_name: PsTube
package_name: pstube
maintainer:
  name: Pratek Sunal
  email: prateek@sunal.in
priority: optional
section: x11
essential: false
license: GPLv3
icon: assets/pstube.png
installed_size: 36000

include_build_number: false

metainfo: linux/packaging/pstube.appdata.xml

desktop_file: linux/packaging/pstube.desktop

dependencies:
  - libmpv1

keywords:
  - PsTube
  - FluTube
  - YouTube
  - Piped
  - Watch

generic_name: PsTube

categories:
  - Utility

startup_notify: false